# Output warning on match but continue

warn:
  - '(?i)user(name)?\W*[:=,]\W*.+$'
  - '\/Users\/\w+\/'

# Fail immediately upon match
fail:
  - '(?i)db_(user(name)?|pass(word)?|name)\W*[:=,]\W*.+$'
  - '(?i)pass(word)?\W*[:=,]\W*.+$'
  - '(A3T[A-Z0-9]|AKIA|AGPA|AIDA|AROA|AIPA|ANPA|ANVA|ASIA)[A-Z0-9]{16}'
  - ''(?i)aws(.{0,20})?(?-i)['\"][0-9a-zA-Z\/+]{40}['\"]''
  - 'amzn\.mws\.[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}'
  - '(?i)(aws_access_key_id|aws_secret_access_key)(.{0,20})?=.[0-9a-zA-Z\/+]{20,40}'
  - '-----BEGIN EC PRIVATE KEY-----'
  - '''(?i)(facebook|fb)(.{0,20})?(?-i)['\"][0-9a-f]{32}['\"]''''
  - '''(?i)(facebook|fb)(.{0,20})?['\"][0-9]{13,17}['\"]'''
  - '''(?i)twitter(.{0,20})?['\"][0-9a-z]{35,44}['\"]'''
  - '''(?i)twitter(.{0,20})?['\"][0-9a-z]{18,25}['\"]'''
  - '''(?i)github(.{0,20})?(?-i)['\"][0-9a-zA-Z]{35,40}['\"]'''
  - '''(?i)linkedin(.{0,20})?(?-i)['\"][0-9a-z]{12}['\"]'''
  - '''(?i)linkedin(.{0,20})?['\"][0-9a-z]{16}['\"]'''
  - 'xox[baprs]-([0-9a-zA-Z]{10,48})?'
  

# Skip on matched filename
skip:
  - '.githound.yml'