# Output warning on match but continue
warn:
  - '(?i)user(name)?\W*[:=,]\W*.+$'
  - '\/Users\/\w+\/'

# Fail immediately upon match
fail:
  - '(?i)db_(user(name)?|pass(word)?|name)\W*[:=,]\W*.+$'
  - '''[g|G][i|I][t|T][h|H][u|U][b|B].{0,30}['\"\\s][0-9a-zA-Z]{35,40}['\"\\s]'''
  - '(\"client_secret\":\"[a-zA-Z0-9-_]{24}\")'
  - '-----BEGIN PGP PRIVATE KEY BLOCK-----'
  - '-----BEGIN EC PRIVATE KEY-----'
  - '-----BEGIN DSA PRIVATE KEY-----'
  - '-----BEGIN OPENSSH PRIVATE KEY-----'

# Skip on matched filename
skip:
  - '.githound.yml'