language: python
jobs:
  include:
    - name: "Python 3.6.12 on Xenial Linux"
      python: 3.6.12
    - name: "Python 3.7.9 on Xenial Linux"
      python: 3.7.9
    - name: "Python 3.8.7 on Xenial Linux"
      python: 3.8.7
    - name: "Python 3.9.0 on Xenial Linux"
      python: 3.9.0
    - name: "Python 3.9.1 on Xenial Linux"
      python: 3.9.1

before_install:
  - python --version
  - pip install -U pip
  - pip install pytest-flake8
  - pip install safety
  - pip install pycodestyle

install:
  - pip install -r requirements.txt

script: 
  - python3 PyFuscation.py || python PyFuscation.py
  - pytest --flake8
  - safety check
  - pycodestyle PyFuscation.py

