arch: amd64
os: linux
dist: focal
language: python
cache: pip
python:
  - "3.6.12"
  - "3.7.9"
  - "3.8.7"
  - "3.9.0"
  - "3.9.1"
  - "pypy3"

jobs:
  include:
      - name: "Compliance: Code Qualily"
        # The idea is to separate Code Quality checks as 
        # - Some libraries are not available for all version of Python
        # - The source code is the same and there is almost no changes in 
        script:
          # Install Flake8 (0.63s Using cached)
          - pip install pycodestyle
          - pycodestyle PyFuscation.py --ignore "E501, E101, W191"
          # Install black (2.18s Using cached)
          # per-file auto-detection
          - pip install black
          - black --check --diff --color
          # Install 
          - pip install xenon
          - xenon --max-average A --max-modules A --max-absolute C .
          - pip install radon
          - radon cc --min B --max F path .
          - radon mi .

      - name: "Compliance: Semgrep check"
        script: 
          - pip install semgrep
          - semgrep --config=p/bandit .
          - semgrep --config=p/r2c-bug-scan .
          - semgrep --config=p/r2c-best-practices .

  allow_failures:
  - python: "pypy3"

before_install:
  - python --version
  - pip install -U pip
  - pip install safety
  - pip install pytest-flake8

script: python3 PyFuscation.py || python PyFuscation.py

install:
  - pip install -r requirements.txt
  # Safety is tied to the version of Python on which it runs.
  - safety check
  # Flake8 is tied to the version of Python on which it runs.
  # Perform PEP8 naming convention checks
  - pytest --flake8
