language: python
jobs:
  include:
    - name: "Python 3.5.0 on Xenial Linux"
      python: 3.5
    - name: "Python 3.6.0 on Xenial Linux"
      python: 3.6
    - name: "Python 3.7.0 on Xenial Linux"
      python: 3.7
    - name: "Python 3.8.0 on Xenial Linux"
      python: 3.8

before_install:
  - python --version
  - pip install -U pip
  - pip install pytest-flake8
  - pip install safety

install:
  - pip install -r requirements.txt

script: 
  - python3 PyFuscation.py || python PyFuscation.py
  - pytest --flake8
  - safety check

