arch: amd64
os: linux
dist: focal      
language: python
cache: pip       # Cache content the pip content to speed up the build process
python:
  - "3.3.7"
  - "3.4.10"
  - "3.3.7"
  - "3.6.12"
  - "3.7.9"
  - "3.8.7"
  - "3.9.0"
  - "3.9.1"
  - "pypy3"

jobs:
  include:
      - name: "Compliance: Code Quality"
        script:
          # Install & perform black checks ()
          - pip install black
          - black --check --diff --color
          # Install & perform xenon checks
          - pip install xenon
          - xenon --max-average A --max-modules A --max-absolute C .
          # Install & perform radon checks on the current path
          - pip install radon
          - radon cc --min B --max F --show-complexity .
          - radon mi --show .

      - name: "Test: Security check"
        script: 
          # Install & perform safety check (Dependencies check)
          - pip install safety
          - safety check -r requirements
          # Install & perform Semgrep checks (Security check, 
          # , best practices, bug scan ) on the current path
          - pip install semgrep
          - semgrep --config=p/bandit .
          - semgrep --config=p/r2c-bug-scan .
          - semgrep --config=p/r2c-best-practices .
  
  # End-Of-Life
  allow_failures:
  - python: "3.3.7"
  - python: "3.4.10"
  - python: "3.3.7"

before_install:
  # Upgrade to the latest version of pip
  - pip install -U pip
  - pip install flake8

script: 
  # Flake8 is tied to the version of Python on which it runs.
  # Perform PEP8 naming convention checks
  - flake8 
  - python3 PyFuscation.py || python PyFuscation.py

install:
  # Install the requirement to run my code
  - pip install -r requirements.txt