arch: amd64
os: linux
dist: focal
language: python
cache: pip
python:
  - "3.6.12"
  - "3.7.9"
  - "3.8.7"
  - "3.9.0"
  - "3.9.1"
  - "pypy3"

jobs:
  include:
      - name: "Compliance: Check if the code is properly lint"
        script:
          # Install Flake8 (1.20s Using cached)
          - pip install pytest-flake8
          - pytest --flake8
          # Install Flake8 (0.63s Using cached)
          - pip install pycodestyle
          - pycodestyle PyFuscation.py --ignore "E501, E101, W191"
          # Install black (2.18s Using cached)
          - pip install black
          - black --check --diff --color

          - pip install xenon
          - xenon --max-absolute B --max-modules A --max-average A .

      - name: "Compliance: Semgrep check"
        script: 
          - pip install semgrep
          - semgrep --config=p/bandit .
          - semgrep --config=p/r2c-bug-scan .
          - semgrep --config=p/r2c-best-practices .

  allow_failures:
  - python: "pypy3"

before_install:
  - python --version
  - pip install -U pip
  - pip install safety

script: python3 PyFuscation.py || python PyFuscation.py

install:
  - pip install -r requirements.txt
  - safety check
