arch: amd64
os: linux
dist: focal
language: python
cache: pip
python:
  - "3.6.12"
  - "3.7.9"
  - "3.8.7"
  - "3.9.0"
  - "3.9.1"
  - "pypy3"

jobs:
  include:
      - name: "Compliance: Check if the code is properly lint"
        script:
          - pytest --flake8
          - pycodestyle PyFuscation.py --ignore "E501, E101, W191"
          - black --check --diff --color
          - isort **/*.py -c -v
      - name: "Compliance: Semgrep check"
        script: 
          - semgrep --config=p/bandit .
          - semgrep --config=p/r2c-bug-scan .
          - semgrep --config=p/r2c-best-practices .

  allow_failures:
  - python: "pypy3"

before_install:
  - python --version
  - pip install -U pip
  - pip install pytest-flake8
  - pip install safety
  - pip install pycodestyle
  - pip install semgrep
  - pip install black
  - pip install isort


script: python3 PyFuscation.py || python PyFuscation.py

install:
  - pip install -r requirements.txt
  - safety check
